/** Action-plan cards keyed by internal trigger IDs. Keys are also used for saved action items. */

export const RECOMMENDATIONS = {
  q1_come_up_short: {
    title: "Stop the monthly shortfall",
    section: "Banking Access",
    problem: "You are running out of money before the month is over.",
    paragraphs: [
      "That usually means normal bills are already bigger than your take-home pay, or they are landing before your money does.",
      "The goal right now is not a perfect budget. It is getting to a tiny amount of breathing room so you are not borrowing for basics.",
    ],
    bullets: [
      "Pick **one** recurring bill to cancel, pause, or renegotiate.",
      "Set a weekly grocery number you can actually live with, even if it is not perfect.",
      "Move bill due dates if timing is the reason your account dips below zero.",
    ],
    research: "(Household spending data shows essentials can take up almost all income for lower-income households.)",
    why: "If basics cost more than your income, even small surprises can turn into debt.",
    doFirst: "Cancel or renegotiate one recurring charge this week, then set a **$10** payday transfer to savings.",
    jargonKey: "financial_stress",
  },
  q1_barely_anything: {
    title: "Create a little breathing room",
    section: "Banking Access",
    problem: "You usually have almost nothing left after bills and essentials.",
    paragraphs: [
      "That does not mean you are bad with money. It means one random expense can wipe out the whole month.",
      "A good first target is a repeatable **$50 to $100** left over each month. That small gap can keep a car repair, fee, or late bill from turning into more debt.",
    ],
    bullets: [
      "Write down next month's bill dates.",
      "Look for one bill that can move closer to payday.",
      "Choose one small spending category to cap for the next **2 weeks**.",
    ],
    research: "(People with even a small cash buffer report less stress around surprise expenses.)",
    why: "A small predictable cushion is cheaper than covering every surprise with credit.",
    doFirst: "Put next month's bills on a calendar today and mark which ones hit before payday.",
    jargonKey: "financial_stress",
  },
  q1_little_inconsistent: {
    title: "Make leftover money automatic",
    section: "Banking Access",
    problem: "You sometimes have money left over, but it does not turn into consistent savings.",
    paragraphs: [
      "This is a good problem to fix because the money is already showing up sometimes.",
      "The trick is to move some of it before it gets absorbed into random spending. Start small enough that you will not cancel it later.",
    ],
    bullets: [
      "Use a separate savings account if you have one.",
      "Schedule the transfer **2 or 3 days** after payday.",
      "Start with half of what you usually have left, or just **$10** if you are not sure.",
    ],
    research: "(Automated savers are more likely to keep an emergency buffer.)",
    why: "Automation turns good months into progress without asking you to make the same choice over and over.",
    doFirst: "Set one automatic transfer for your next payday, even if it is only **$10**.",
    jargonKey: "savings_automation",
  },
  q2_income_unsteady: {
    title: "Plan for slow-income months",
    section: "Emergency Preparedness",
    problem: "Your income changes enough that a slow month can throw everything off.",
    paragraphs: [
      "When income is uneven, the danger is not just making less. It is having rent, bills, and payments stay the same while your paycheck changes.",
      "Use strong months to prepay the stress of slow months. Think of this money as your future paycheck, not extra spending money.",
    ],
    bullets: [
      "Create a separate buffer for slow months.",
      "Save **10% to 15%** from stronger pay periods if you can.",
      "Use that buffer only when income dips, not for normal shopping.",
    ],
    research: "(Workers with unpredictable income are more likely to rely on credit when they do not have a buffer.)",
    why: "A slow-month fund keeps one low paycheck from turning into credit card debt.",
    doFirst: "The next time you have a stronger paycheck, move **10%** into a separate slow-month buffer before spending.",
    jargonKey: "income_stability",
  },
  q5_debt_stressed: {
    title: "Get ahead of stressful debt",
    section: "Emergency Preparedness",
    problem: "Your debt payments are starting to feel stressful.",
    paragraphs: [
      "If you are still making payments, you have more options than you think. It is much easier to ask for help before you miss a payment.",
      "You do not need to solve every balance this week. You need to stop the situation from getting worse.",
    ],
    bullets: [
      "Ask about a lower payment, hardship plan, or changed due date.",
      "Write down what you can realistically pay each month.",
      "Prioritize any account that is close to becoming late.",
    ],
    research: "(Borrowers who contact creditors early usually have more repayment options.)",
    why: "Late fees and credit score damage make the same debt harder to deal with later.",
    doFirst: "Call or message one creditor this week and ask what lower-payment options are available.",
  },
  q6_emergency_hard: {
    title: "Make a plan for a $900 surprise",
    section: "Emergency Preparedness",
    problem: "A **$900** emergency would be hard to handle right now.",
    paragraphs: [
      "That is stressful, but the first step is not magically having $900 tomorrow. The first step is knowing what order you would try things in.",
      "A plan keeps you from choosing the most expensive option just because you are panicking.",
    ],
    bullets: [
      "Check what cash you could use without missing rent or bills.",
      "Know your cheapest backup option before an emergency happens.",
      "Decide which non-urgent expense you would pause first.",
    ],
    research: "(People with savings access are much more likely to cover surprise expenses without new debt.)",
    why: "A written plan can lower the cost of an emergency even before your savings are perfect.",
    doFirst: "Write your **3-step** emergency order today: cash first, cheapest backup second, paused expense third.",
    jargonKey: "emergency_fund",
  },
  q7_buffer_thin: {
    title: "Build your first safety cushion",
    section: "Emergency Preparedness",
    problem: "Your emergency buffer is too thin for a job loss, bill shock, or income gap.",
    paragraphs: [
      "Do not start with a huge goal if that makes you freeze. Start with one week of must-pay expenses.",
      "Once you can protect one week, you can build toward **1 month**, then **3 months**. If your income is irregular, your long-term target should be closer to **6 months**.",
    ],
    bullets: [
      "Use a separate account if possible.",
      "Name it Emergency so it does not feel like spending money.",
      "Add a small amount every payday or every Friday.",
    ],
    research: "(Households with emergency funds are more likely to keep saving even when life gets bumpy.)",
    why: "A visible cushion gives you options before you have to borrow.",
    doFirst: "Schedule a repeating **$25** transfer every Friday or every payday.",
    jargonKey: "emergency_fund",
  },
  q3_credit_carry: {
    title: "Stop the card balance from growing",
    section: "Spending Behavior",
    problem: "You are carrying a credit card balance, which means you are paying interest on things you already bought and used.",
    paragraphs: [
      "Here is what that actually costs you:",
      "The goal right now is not to pay it all off immediately. It is to stop the balance from growing.",
    ],
    bullets: [
      "A **$1,000** balance on a **24% APR** card costs about **$20** every month in interest, even if you buy nothing new.",
      "The longer the balance sits, the more you pay for things that are already gone.",
      "New purchases make it harder to see whether your payoff plan is working.",
    ],
    research: "(Credit card interest is one of the fastest ways small balances become expensive.)",
    why: "Freezing new charges gives you a clear starting point for paying the balance down.",
    doFirst: "Remove your card from saved payment methods this week and send any extra cash to your smallest balance or highest-interest card.",
    jargonKey: "credit_interest",
  },
  q4_bnpl_stack: {
    title: "Get BNPL payments under control",
    section: "Spending Behavior",
    problem: "You are using Buy Now Pay Later for purchases. Here is what that means for your finances day to day.",
    paragraphs: [
      "BNPL can make a purchase feel smaller than it really is because the payment gets split up.",
      "The problem is that several small payments can hit your account around rent, groceries, or payday gaps.",
    ],
    bullets: [
      "**1** plan is easy to forget.",
      "**2 or more** plans can act like extra bills you did not budget for.",
      "A **$25** payment here and a **$40** payment there can quietly eat the money you thought was available.",
      "Late fees or overdrafts can make the original purchase more expensive.",
    ],
    research: "(BNPL users tend to have lower emergency savings than non-users.)",
    why: "Seeing every payment date makes BNPL feel like real bills again.",
    doFirst: "List every active BNPL plan, payment amount, and due date in one note today.",
    jargonKey: "bnpl",
  },
  q8_avoid_tracking: {
    title: "Make checking your money less stressful",
    section: "Financial Literacy",
    problem: "You are avoiding your balance or spending, so small problems can sneak up on you.",
    paragraphs: [
      "Avoiding money usually means it feels stressful to look, not that you do not care.",
      "Make the check-in small enough that you will actually do it. You do not need a full budget app to start.",
    ],
    bullets: [
      "Check once a week for **15 minutes**.",
      "Look at only **3** categories: groceries, essentials, and fun spending.",
      "Write the totals down without judging yourself.",
    ],
    research: "(People often underestimate flexible spending when they do not track it.)",
    why: "A short weekly check-in gives you time to adjust before fees or debt show up.",
    doFirst: "Set a **15-minute** calendar reminder for Sunday and review only those **3** spending categories.",
  },
  q9_low_savings_discipline: {
    title: "Save before the money disappears",
    section: "Financial Literacy",
    problem: "Saving only when there is money left over is not working consistently.",
    paragraphs: [
      "That is normal. Money that looks available usually gets used by the end of the month.",
      "Treat savings like a bill you pay yourself first. The amount can be small, but the timing matters.",
    ],
    bullets: [
      "Move money on payday, not at the end of the month.",
      "Start with **$10** or **$25** if cash is tight.",
      "Increase it later only after the habit feels easy.",
    ],
    research: "(People who automate savings are more likely to keep a buffer through income changes.)",
    why: "Automatic saving removes the monthly decision and protects the money before it gets spent.",
    doFirst: "Set an automatic payday transfer for **$10** or **$25** before your next paycheck arrives.",
    jargonKey: "savings_automation",
  },
};
